# -*- coding: utf-8 -*-
"""Assemble the one shippable skill from the six source folders.

The six folders are the source: each is a coherent thing to edit. This builds
them into a single skill so a colleague has one upload and no structure to
learn. Nothing here is authored by hand except router.md, so the source and
the shipped form cannot drift apart.

    py -X utf8 build_package.py
"""
import io, os, re, shutil, stat, sys, time, zipfile

BASE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(BASE, "src")
OUT = None            # set below, from NAME, so the two cannot drift
SITE = os.path.join(os.path.dirname(BASE), "cost_behavior_revamp", "skills")

# Stamped into every generated file. Someone who opens the built skill to fix
# a typo has no way of knowing their change will be deleted by the next build -
# unless the file says so. GENERATED_MARK also exempts these lines from the
# stale-name check below, since the pointer necessarily names a source folder.
GENERATED_MARK = "Generated from src/"
HTML_STAMP = ("<!-- %s%s - do not edit this file.\n"
              "     Your change will be deleted by the next build.\n"
              "     Edit the source file, then run: python build_package.py -->\n\n")
PY_STAMP = ("# %s%s - do not edit this file.\n"
            "# Your change will be deleted by the next build.\n"
            "# Edit the source file, then run: python build_package.py\n")

NAME = "teaching-with-ai"
OUT = os.path.join(BASE, NAME)
DESCRIPTION = (
    "Everything a teacher needs to work with an AI on their own teaching "
    "material: understanding what is there, changing it, building cases, "
    "checking it, and publishing it without leaking the answers. Use when "
    "someone shares a lecture in PowerPoint, PDF or LaTeX, a notebook, a "
    "syllabus, an assignment or a whole course folder and asks what to "
    "improve; when making a session more interactive; when turning a lecture "
    "into something students run; when "
    "designing a case where students critique a flawed answer before being "
    "taught the topic; when building practice datasets that rotate each year; "
    "when rewriting assessment an AI can now answer in a minute; or when "
    "editing the slide file itself. Also use for any question about working "
    "with AI on academic work, such as what to disclose, how to check what it "
    "produced, which tasks a teacher must never hand over, or how to set an "
    "AI policy for staff; and for verifying citations, checking numbers "
    "against their source, or asking whether an answer key could leak."
)

# source SKILL.md  ->  the reference file it becomes
STAGES = [
    ("ai-teaching-guardrails", "guardrails.md"),
    ("course-audit", "audit.md"),
    ("course-rebuild", "rebuild.md"),
    ("case-authoring", "case.md"),
    ("verify-claims", "verify.md"),
    ("safe-to-publish", "publish.md"),
]

# Every cross-reference the merge invalidates. Two kinds, and the phrase
# rewrites must come first so they can still match the original wording before
# the bare names inside them are replaced.
#
# The second kind matters as much as the first: once six skills become seven
# files, prose that says "that skill" or "the file next to this one" is no
# longer true, and a mechanical rename alone leaves it stranded.
REWRITES = [
    # --- prose the merge makes untrue ---
    ("Its companion file,\n`case-authoring/BUILDING.md`, has the folder that "
     "makes it run and the rule that\nthe marking scheme never ships.",
     "The building section of\n`reference/case.md` has the folder that makes "
     "it run, and the rule that\nthe marking scheme never ships."),
    ("That skill carries the design rules",
     "That file carries the design rules"),
    ("This skill does **not** work through a checklist.",
     "This stage does **not** work through a checklist."),
    ("This skill checks a draft's citations",
     "This part of the skill checks a draft's citations"),
    ("The `course-audit` and `course-rebuild` skills assume these rules; this "
     "skill states them, and stands on its own for anything else.",
     "Every other part of this skill assumes these rules; this file states "
     "them, and stands on its own for anything else."),
    ("Two further things are\nneeded before one exists, and they are in the "
     "file next to this one:",
     "Two further things are\nneeded before one exists:"),
    ("## Local addition: building the case",
     "## Local addition: what else a case needs"),
    ("A companion to `SKILL.md`. That file decides what the case should "
     "contain; this\none turns the decision into a folder that runs. Read it "
     "second.",
     "The rules above decide what the case should contain. This section turns\n"
     "that decision into a folder that runs."),
    ("## Step 4 — The audit exercise: use the case skill",
     "## Step 4 — The audit exercise: use the case rules"),
    ("those two are merged into a single skill, **`safe-to-publish`** —\nsame "
     "two patterns, one file.",
     "those two are merged, and both patterns are in\n**`reference/publish.md`**."),
    # --- names of things that are now files ---
    ("**`BUILDING.md`**", "**The building section below**"),
    ("Read `BUILDING.md` once the design questions above are settled.",
     "Read the building section below once the design questions above are settled."),
    ("`course-audit`", "`reference/audit.md`"),
    ("`course-rebuild`", "`reference/rebuild.md`"),
    ("`case-authoring`", "`reference/case.md`"),
    ("`verify-claims`", "`reference/verify.md`"),
    ("`safe-to-publish`", "`reference/publish.md`"),
]

# Names that must not survive into the built skill.
FORBIDDEN = ["course-audit", "course-rebuild", "case-authoring",
             "verify-claims", "safe-to-publish", "ai-teaching-guardrails",
             "BUILDING.md"]

# The upstream body ships verbatim and legitimately names upstream's own skill
# folders; the addendum below this fence explains the rename. Exempt from the
# FORBIDDEN check, and never rewritten.
FENCE = "<!-- The body above this line is the upstream skill"

fail = []
fired = set()


def strip_frontmatter(text):
    if not text.startswith("---"):
        return text
    return text[text.index("\n---", 3) + 4:].lstrip("\n")


def rewrite(text):
    for old, new in REWRITES:
        if old in text:
            fired.add(old)
            text = text.replace(old, new)
    return text


def write(rel, text, source):
    p = os.path.join(OUT, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    io.open(p, "w", encoding="utf-8").write(
        (HTML_STAMP % (GENERATED_MARK, source)) + text.rstrip() + "\n")


def build_reference():
    for folder, dest in STAGES:
        body = strip_frontmatter(io.open(
            os.path.join(SRC, folder, "SKILL.md"), encoding="utf-8").read())

        if folder == "case-authoring":
            # Rewrite only what follows the fence; the upstream body above it
            # must stay byte-identical. Then fold BUILDING.md in below.
            head, sep, tail = body.partition(FENCE)
            body = head + sep + rewrite(tail)
            bm = rewrite(io.open(os.path.join(SRC, folder, "BUILDING.md"),
                                 encoding="utf-8").read())
            # BUILDING.md is a standalone document. Nest every heading a level
            # down so its title becomes a section of this file rather than a
            # rival to it, and its steps sit under that title.
            bm = re.sub(r"(?m)^(#{1,5}) ", r"#\1 ", bm)
            body = body.rstrip() + "\n\n---\n\n" + bm.lstrip()
        else:
            body = rewrite(body)

        src = "%s/SKILL.md" % folder
        if folder == "case-authoring":
            src = "%s/SKILL.md + BUILDING.md" % folder
        write("reference/" + dest, body, src)

    write("reference/activities.md", rewrite(io.open(
        os.path.join(SRC, "course-rebuild", "reference", "activities.md"),
        encoding="utf-8").read()), "course-rebuild/reference/activities.md")


def build_scripts():
    dst = os.path.join(OUT, "scripts")
    os.makedirs(dst, exist_ok=True)
    for folder in set(f for f, _ in STAGES) | {"course-rebuild"}:
        s = os.path.join(SRC, folder, "scripts")
        if os.path.isdir(s):
            for fn in sorted(os.listdir(s)):
                if not fn.endswith(".py"):
                    continue
                body = io.open(os.path.join(s, fn), encoding="utf-8").read()
                # keep any shebang or coding line first, or python stops
                # honouring them
                lines = body.split("\n")
                keep = 0
                while keep < len(lines) and (lines[keep].startswith("#!")
                                             or "coding" in lines[keep][:30]):
                    keep += 1
                stamp = PY_STAMP % (GENERATED_MARK, "%s/scripts/%s" % (folder, fn))
                out = "\n".join(lines[:keep] + [stamp] + lines[keep:])
                io.open(os.path.join(dst, fn), "w", encoding="utf-8").write(out)
    return sorted(os.listdir(dst))


def build_skill_md():
    if len(DESCRIPTION) > 1024:
        fail.append("description is %d chars, over the 1024 limit" % len(DESCRIPTION))
    router = io.open(os.path.join(SRC, "router.md"), encoding="utf-8").read()
    # the stamp goes after the frontmatter, never before it: a skill whose
    # file does not open with --- has no frontmatter at all
    io.open(os.path.join(OUT, "SKILL.md"), "w", encoding="utf-8").write(
        "---\nname: %s\ndescription: %s\n---\n\n%s%s"
        % (NAME, DESCRIPTION, HTML_STAMP % (GENERATED_MARK, "router.md"),
           router.lstrip()))


def check():
    """Refuse to ship a skill whose routing is broken. Three ways it can be:
    a reference named but missing, one present but never routed to, or a
    stale skill name left pointing at a folder that no longer exists."""
    skill = io.open(os.path.join(OUT, "SKILL.md"), encoding="utf-8").read()
    named = set(re.findall(r"`reference/([a-z]+\.md)`", skill))
    present = set(os.listdir(os.path.join(OUT, "reference")))

    for m in sorted(named - present):
        fail.append("SKILL.md points at reference/%s, which does not exist" % m)
    for m in sorted(present - named):
        fail.append("reference/%s exists but SKILL.md never says when to read it" % m)

    for fn in sorted(present):
        t = io.open(os.path.join(OUT, "reference", fn), encoding="utf-8").read()
        # the stamp names the source file on purpose, so it is not a stale
        # reference; drop those lines before looking for one
        t = "\n".join(l for l in t.split("\n") if GENERATED_MARK not in l)
        parts = t.split(FENCE)
        checkable = parts[0] + parts[-1] if len(parts) > 1 else t
        for bad in FORBIDDEN:
            if bad in checkable:
                fail.append("reference/%s still refers to '%s'" % (fn, bad))

    # every generated file must carry the stamp, or the warning is only on
    # the ones somebody remembered
    for root, dirs, files in os.walk(OUT):
        for f in sorted(files):
            p = os.path.join(root, f)
            rel = os.path.relpath(p, OUT).replace("\\", "/")
            if GENERATED_MARK not in io.open(p, encoding="utf-8").read():
                fail.append("%s is generated but carries no stamp" % rel)

    for fn in sorted(set(re.findall(r"`?scripts/([a-z_]+\.py)", skill))):
        if not os.path.exists(os.path.join(OUT, "scripts", fn)):
            fail.append("SKILL.md names scripts/%s, which was not copied" % fn)

    # A rewrite that no longer matches has stopped doing its job silently, and
    # the prose it was fixing has quietly reverted. Someone edited the source.
    for old, _ in REWRITES:
        if old not in fired:
            fail.append("this rewrite matched nothing, so the source wording "
                        "changed under it: %r" % (old[:60] + "..."))


def build_zip():
    z_dir = os.path.join(BASE, "zips")
    os.makedirs(z_dir, exist_ok=True)
    # zips/ is generated, so this owns it. A retired zip left lying about is
    # one a colleague can still download, and it will be the wrong package.
    retired = [f for f in sorted(os.listdir(z_dir)) if f != NAME + ".zip"]
    for f in retired:
        os.remove(os.path.join(z_dir, f))
    out = os.path.join(z_dir, NAME + ".zip")
    n = 0
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for root, dirs, files in os.walk(OUT):
            dirs[:] = [d for d in dirs if d != "__pycache__"]
            for fn in sorted(files):
                full = os.path.join(root, fn)
                z.write(full, os.path.relpath(full, OUT).replace("\\", "/"))
                n += 1
        for d in ("README.md", "LICENSE", "UPSTREAM-LICENSE"):
            p = os.path.join(BASE, d)
            if os.path.exists(p):
                z.write(p, d)
                n += 1
    with zipfile.ZipFile(out) as z:
        if "SKILL.md" not in z.namelist():
            fail.append("SKILL.md is not at the root of the zip")
    return out, n, os.path.getsize(out) / 1024.0, retired


def clear_output():
    """Delete the generated folder before rebuilding it.

    On Windows this fails intermittently with WinError 32 - Dropbox syncing
    the folder, an indexer, an editor with a file open. A recursive delete
    that dies halfway leaves a half-built skill on disk, which is worse than
    not rebuilding at all, so retry rather than let it through. Each retry
    resumes where the last one stopped.
    """
    if not os.path.isdir(OUT):
        return

    def on_error(func, path, _):
        # a read-only file refuses os.remove until the bit is cleared
        try:
            os.chmod(path, stat.S_IWRITE)
            func(path)
        except OSError:
            pass

    last = None
    for attempt in range(6):
        try:
            shutil.rmtree(OUT, onerror=on_error)
            if not os.path.isdir(OUT):
                return
        except OSError as e:
            last = e
        time.sleep(0.4)

    print("Could not clear %s" % OUT)
    print("  %s" % last)
    print("Something is holding a file open - Dropbox mid-sync, an editor, or")
    print("a virus scanner. Close it and run again. The folder may be partly")
    print("deleted, so do not install from it until a build has succeeded.")
    sys.exit(1)


clear_output()

build_reference()
scripts = build_scripts()
build_skill_md()
check()

print("BUILT  %s/" % NAME)
words = lambda p: len(io.open(p, encoding="utf-8").read().split())
print("  %-24s %5d words   description %d chars"
      % ("SKILL.md", words(os.path.join(OUT, "SKILL.md")), len(DESCRIPTION)))
tot = 0
for fn in sorted(os.listdir(os.path.join(OUT, "reference"))):
    w = words(os.path.join(OUT, "reference", fn))
    tot += w
    print("  reference/%-14s %5d words" % (fn, w))
print("  %-24s %5d words deferred, read only when needed" % ("", tot))
print("  scripts/                 %s" % ", ".join(scripts))

path, n, kb, retired = build_zip()
print()
if retired:
    print("RETIRED  removed from zips/, so nobody downloads the old shape:")
    for f in retired:
        print("           %s" % f)
    print()
if fail:
    print("CHECKS FAILED - built, but must not be shipped:")
    for f in fail:
        print("   * %s" % f)
    sys.exit(1)
print("checks passed:  every reference is routed to and exists")
print("                no stale skill name survives outside the verbatim block")
print("                every script named in SKILL.md is present")
print("ZIP    %s   %d files   %.1f KB" % (os.path.basename(path), n, kb))

if os.path.isdir(os.path.dirname(SITE)):
    os.makedirs(SITE, exist_ok=True)
    for f in sorted(os.listdir(SITE)):
        os.remove(os.path.join(SITE, f))
    shutil.copy2(path, os.path.join(SITE, os.path.basename(path)))
    print("SITE   skills/ now holds one file, with every retired zip removed")
