#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Generated from src/course-audit/scripts/read_material.py - do not edit this file.
# Your change will be deleted by the next build.
# Edit the source file, then run: python build_package.py

"""
read_material.py - count what is actually in a piece of teaching material.

Handles:
    .pptx       PowerPoint       - repeats, questions, notes, density
    .pdf        exported slides or a document      (needs pypdf)
    .tex        LaTeX / beamer   - frames, overlays, \\note
    .ipynb      notebooks        - how much the student actually writes
    a folder    a course or repo - inventory and the conventions it follows

Slides are slides whatever made them, so .pptx, .pdf and .tex all go through
one analyser: the same repeat detector, the same question count, the same
density measure. Only the speaker-notes source differs.

Why this exists: a language model asked to audit teaching material produces
numbers that are approximately right and quietly wrong. This opens the files
and counts. Everything printed is either measured or labelled as a guess.

Usage:
    python read_material.py "My Lecture.pptx"
    python read_material.py lecture.pdf --json audit.json
    python read_material.py slides.tex
    python read_material.py ./course_repo

Standard library only, except .pdf which uses pypdf if it is installed:
    py -m pip install pypdf
On Windows the interpreter is usually  py -X utf8  rather than  python.
"""

import argparse
import json
import os
import re
import sys
import zipfile
from xml.etree import ElementTree as ET

A = "{http://schemas.openxmlformats.org/drawingml/2006/main}"
URL = re.compile(r"https?://\S+|www\.\S+")

STAGE_WORDS = re.compile(
    r"\b(draw|drew|sketch|annotate|circle|underline|board|whiteboard|ipad|"
    r"tablet|connect|highlight|point at|show on|write on|compare)\b", re.I)
TODO_WORDS = re.compile(r"(^\s*!|\bcheck\b[^.]*\btextbook\b|\btodo\b|\badd later\b)", re.I)
FILLIN = re.compile(r"\(\s*\w+\s*/\s*\w+\s*\)|_{3,}")

STOP = set("""a an the and or of to in on for with is are was were be been being as at by from
that this these those it its our your their we you they he she i not no if then than so such
into over under about but can could may might will would shall should do does did have has had""".split())

MIN_TOKENS_TO_JUDGE = 8
CONTAINMENT = 0.90
DENSE_WORDS = 60          # a slide above this is doing a document's job

BLANK_MARK = re.compile(
    r"(#\s*(your|todo|fill|complete|write|exercise|task)\b"
    r"|\byour (prompt|code|answer|model|turn)\b"
    r"|raise\s+NotImplementedError"
    r"|\.\.\.\s*$"
    r"|#\s*_{3,}"
    r"|<\s*fill[^>]*>)", re.I | re.M)
DO_NOT_CHANGE = re.compile(r"do not (change|edit|modify)", re.I)
ABS_PATH = re.compile(r"""["'](?:[A-Za-z]:[\\/]|/Users/|/home/|/mnt/)[^"']*["']""")
SECRET = re.compile(r"""(sk-[A-Za-z0-9]{12,}|api[_-]?key\s*=\s*["'][^"']{8,}["']|token\s*=\s*["'][^"']{12,}["'])""", re.I)
READS_FILE = re.compile(r"""(?:read_csv|read_excel|open|read_json|load|imread)\s*\(\s*["']([^"']+)["']""")
RAW_URL = re.compile(r"raw\.githubusercontent\.com|githubusercontent")
STDLIB = set("""os sys re json csv math random time datetime pathlib itertools collections
functools statistics zipfile io typing warnings argparse subprocess glob shutil textwrap
base64 hashlib urllib string decimal fractions copy pprint""".split())


# ======================================================= shared slide model ==
def slide(n, paras, title=None, images=0, animated=False, builds=0):
    text = " ".join(paras)
    words = re.findall(r"[A-Za-z][A-Za-z'-]+", text)
    return {"n": n, "paras": paras, "title": title if title is not None else (paras[0] if paras else ""),
            "text": text, "tokens": tokens(paras), "words": len(words),
            "images": images, "animated": animated, "builds": builds}


def tokens(paras):
    words = re.findall(r"[a-z]{2,}", " ".join(paras).lower())
    return set(w for w in words if w not in STOP)


def containment(a, b):
    if not a or not b:
        return 0.0
    return len(a & b) / float(min(len(a), len(b)))


def mark_distinctive(slides):
    df = {}
    for s in slides:
        for t in s["tokens"]:
            df[t] = df.get(t, 0) + 1
    limit = max(3, int(round(0.25 * len(slides))))
    for s in slides:
        s["distinctive"] = set(t for t in s["tokens"] if df[t] <= limit)


def group_slides(slides):
    groups = [[slides[0]["n"]]] if slides else []
    heads = [slides[0]] if slides else []
    unsure = []
    for cur in slides[1:]:
        head = heads[-1]
        same_title = bool(cur["title"]) and cur["title"].lower() == head["title"].lower()
        small = min(len(cur["distinctive"]), len(head["distinctive"]))
        c = containment(cur["distinctive"], head["distinctive"])
        if cur["text"] and cur["text"] == head["text"]:
            groups[-1].append(cur["n"]);  continue
        if same_title and small >= MIN_TOKENS_TO_JUDGE and c >= CONTAINMENT:
            groups[-1].append(cur["n"]);  continue
        if same_title and small < MIN_TOKENS_TO_JUDGE:
            unsure.append({"slide": cur["n"], "group_head": head["n"],
                           "why": "both carry the same heading and one has almost no text "
                                  "of its own, so the script cannot see it"})
        groups.append([cur["n"]]);  heads.append(cur)
    return groups, unsure


def norm_q(q):
    return re.sub(r"[^a-z0-9 ]", "", q.lower()).strip()


def find_questions(slides, repeats):
    rows, seen, uniq = [], set(), 0
    for s in slides:
        qs = [p for p in s["paras"] if "?" in p]
        fills = [p for p in s["paras"] if FILLIN.search(p)]
        if not qs and not fills:
            continue
        new_here = 0
        for q in qs:
            k = norm_q(q)
            if k and k not in seen:
                seen.add(k); new_here += 1; uniq += 1
        rows.append({"slide": s["n"], "question_marks": s["text"].count("?"),
                     "new_questions": new_here, "fill_in_blanks": len(fills),
                     "repeat_slide": s["n"] in repeats, "examples": (qs + fills)[:3]})
    return rows, uniq


def classify_note(text):
    if not text or re.fullmatch(r"[\d\s]*", text):
        return "empty"
    if TODO_WORDS.search(text):
        return "to-do left in the file"
    if STAGE_WORDS.search(text):
        return "stage direction (live drawing)"
    if len(text.split()) <= 6:
        return "short fragment - check it"
    return "narration"


def analyse_slides(slides, notes, kind, extra=None):
    """Everything that is true of a deck whatever produced it."""
    if not slides:
        return {"kind": kind, "error": "no slides or frames found"}
    mark_distinctive(slides)
    groups, unsure = group_slides(slides)
    repeats = [n for g in groups for n in g[1:]]
    rows, uniq = find_questions(slides, set(repeats))

    kinds = ["narration", "stage direction (live drawing)", "short fragment - check it",
             "to-do left in the file", "empty"]
    by_kind = dict((k, []) for k in kinds)
    for n, t in sorted(notes.items()):
        by_kind[classify_note(t)].append((n, t))

    words = [s["words"] for s in slides]
    dense = [(s["n"], s["words"]) for s in slides if s["words"] > DENSE_WORDS]
    builds = sum(s.get("builds", 0) for s in slides)

    out = {
        "kind": kind,
        "slides_total": len(slides), "distinct_slides": len(groups),
        "repeat_slides": repeats, "groups": [g for g in groups if len(g) > 1],
        "needs_human_check": unsure,
        "unique_questions": uniq,
        "question_marks_total": sum(r["question_marks"] for r in rows),
        "fill_in_blanks": sum(r["fill_in_blanks"] for r in rows),
        "questions_by_slide": rows,
        "notes_pages": len(notes), "slides_with_no_notes": len(slides) - len(notes),
        "notes_by_kind": dict((k, [n for n, _ in v]) for k, v in by_kind.items()),
        "notes_text": by_kind,
        "words_total": sum(words),
        "words_median": sorted(words)[len(words) // 2] if words else 0,
        "words_max": max(words) if words else 0,
        "dense_slides": dense,
        "in_file_builds": builds,
        "titles": [(s["n"], s["title"][:70]) for s in slides],
    }
    out.update(extra or {})
    return out


# ================================================================== pptx ====
def slide_no(name):
    m = re.search(r"(\d+)", os.path.basename(name))
    return int(m.group(1)) if m else 0


def para_texts(xml_bytes):
    root = ET.fromstring(xml_bytes)
    out = []
    for p in root.iter(A + "p"):
        s = "".join((t.text or "") for t in p.iter(A + "t"))
        s = URL.sub(" ", s)
        s = re.sub(r"\s+", " ", s).strip()
        if s:
            out.append(s)
    return out


def audit_pptx(path):
    z = zipfile.ZipFile(path)
    names = z.namelist()
    parts = sorted([n for n in names if re.match(r"ppt/slides/slide\d+\.xml$", n)],
                   key=slide_no)
    media = [n for n in names if n.startswith("ppt/media/")]

    slides = []
    for i, part in enumerate(parts, start=1):
        xml = z.read(part)
        rels = "ppt/slides/_rels/%s.rels" % os.path.basename(part)
        n_img = len(re.findall(r"\.\./media/", z.read(rels).decode("utf-8", "ignore"))) \
            if rels in names else 0
        slides.append(slide(i, para_texts(xml), images=n_img, animated=b"<p:anim" in xml))

    notes = {}
    for part in sorted([n for n in names
                        if re.match(r"ppt/notesSlides/notesSlide\d+\.xml$", n)], key=slide_no):
        rels = "ppt/notesSlides/_rels/%s.rels" % os.path.basename(part)
        if rels not in names:
            continue
        m = re.search(r'Target="\.\./slides/(slide\d+\.xml)"',
                      z.read(rels).decode("utf-8", "ignore"))
        if not m:
            continue
        body = [p for p in para_texts(z.read(part)) if not re.fullmatch(r"\d+", p.strip())]
        notes[slide_no(m.group(1))] = " ".join(body).strip()
    z.close()

    return analyse_slides(slides, notes, "pptx", {
        "file": os.path.basename(path), "source": "PowerPoint",
        "images": len(media),
        "animated_slides": [s["n"] for s in slides if s["animated"]]})


# =================================================================== pdf ====
def audit_pdf(path):
    try:
        from pypdf import PdfReader
    except ImportError:
        try:
            from PyPDF2 import PdfReader
        except ImportError:
            return {"kind": "pdf", "error":
                    "Reading a PDF needs pypdf.  Install it with:  py -m pip install pypdf\n"
                    "  Or, if the PDF is scanned images with no text layer, do not use this\n"
                    "  script at all - open the PDF in the conversation and read it directly."}
    r = PdfReader(path)
    slides, empty_pages = [], []
    for i, page in enumerate(r.pages, start=1):
        raw = page.extract_text() or ""
        lines = [re.sub(r"\s+", " ", URL.sub(" ", ln)).strip()
                 for ln in raw.splitlines()]
        lines = [ln for ln in lines if ln]
        if not lines:
            empty_pages.append(i)
        slides.append(slide(i, lines))

    med = sorted(s["words"] for s in slides)[len(slides) // 2] if slides else 0
    looks_like_slides = med <= 90
    res = analyse_slides(slides, {}, "pdf", {
        "file": os.path.basename(path),
        "source": "PDF (%s)" % ("slides" if looks_like_slides else "a document"),
        "looks_like_slides": looks_like_slides,
        "pages_with_no_text": empty_pages,
        "images": 0, "animated_slides": []})
    return res


# =================================================================== tex ====
FRAME_RE = re.compile(r"\\begin\{frame\}(.*?)\\end\{frame\}", re.S)
FRAMETITLE = re.compile(r"\\frametitle\s*\{")
OVERLAY = re.compile(r"\\pause\b|\\(?:only|onslide|uncover|visible|alt)\s*<|\\item\s*<\d")


def _balanced(s, start):
    """Return the contents of a {...} group beginning at s[start] == '{'."""
    depth, i = 0, start
    while i < len(s):
        if s[i] == "{":
            depth += 1
        elif s[i] == "}":
            depth -= 1
            if depth == 0:
                return s[start + 1:i], i + 1
        i += 1
    return "", len(s)


def strip_tex(s):
    s = re.sub(r"(?<!\\)%.*", "", s)                       # comments
    s = re.sub(r"\\(?:label|cite[a-z]*|ref|includegraphics|usetikzlibrary)\s*(\[[^\]]*\])?\s*\{[^}]*\}", " ", s)
    s = re.sub(r"\\begin\{(tikzpicture|axis|lstlisting|verbatim)\}.*?\\end\{\1\}", " ", s, flags=re.S)
    s = re.sub(r"\\[a-zA-Z@]+\s*(\[[^\]]*\])?", " ", s)     # remaining commands
    s = re.sub(r"[{}$&~^_\\]", " ", s)
    return re.sub(r"\s+", " ", s).strip()


def audit_tex(path):
    src = open(path, encoding="utf-8", errors="replace").read()
    doc = src
    m = re.search(r"\\begin\{document\}(.*?)\\end\{document\}", src, re.S)
    if m:
        doc = m.group(1)

    frames, notes = [], {}
    for i, mm in enumerate(FRAME_RE.finditer(doc), start=1):
        body = mm.group(1)

        title = ""
        t = FRAMETITLE.search(body)
        if t:
            title = strip_tex(_balanced(body, t.end() - 1)[0])
        else:                                   # \begin{frame}[opts]{Title}
            head = body[:200]
            b = re.match(r"\s*(\[[^\]]*\])?\s*\{", head)
            if b:
                title = strip_tex(_balanced(head, b.end() - 1)[0])

        note = ""
        nm = re.search(r"\\note\s*(\[[^\]]*\])?\s*\{", body)
        if nm:
            note = strip_tex(_balanced(body, nm.end() - 1)[0])
            if note:
                notes[i] = note

        builds = len(OVERLAY.findall(body))
        text = strip_tex(body)
        paras = [p.strip() for p in re.split(r"(?<=[.!?])\s+|\s{3,}", text) if p.strip()]
        if title and (not paras or paras[0] != title):
            paras = [title] + paras
        frames.append(slide(i, paras, title=title, builds=builds))

    sections = [strip_tex(_balanced(doc, mm.end() - 1)[0])
                for mm in re.finditer(r"\\section\*?\s*\{", doc)]
    cls = re.search(r"\\documentclass\s*(\[[^\]]*\])?\s*\{([^}]*)\}", src)

    return analyse_slides(frames, notes, "tex", {
        "file": os.path.basename(path),
        "source": "LaTeX (%s)" % (cls.group(2) if cls else "unknown class"),
        "sections": sections,
        "has_appendix": bool(re.search(r"\\appendix\b", doc)),
        "images": len(re.findall(r"\\includegraphics", doc)),
        "animated_slides": [f["n"] for f in frames if f["builds"]]})


# ============================================================== notebook ====
def audit_ipynb(path):
    with open(path, encoding="utf-8") as f:
        nb = json.load(f)
    cells = nb.get("cells", [])
    md = [c for c in cells if c.get("cell_type") == "markdown"]
    code = [c for c in cells if c.get("cell_type") == "code"]

    def src(c):
        s = c.get("source", "")
        return "".join(s) if isinstance(s, list) else s

    blanks, dnc, empty, abs_paths, secrets, reads = [], [], [], [], [], []
    imports, has_output = set(), 0
    for i, c in enumerate(code, start=1):
        s = src(c)
        if not s.strip():
            empty.append(i)
        if BLANK_MARK.search(s):
            blanks.append(i)
        if DO_NOT_CHANGE.search(s):
            dnc.append(i)
        for m in ABS_PATH.finditer(s):
            abs_paths.append((i, m.group(0)[:70]))
        for m in SECRET.finditer(s):
            secrets.append((i, m.group(0)[:24] + "..."))
        for m in READS_FILE.finditer(s):
            reads.append((i, m.group(1)))
        for m in re.finditer(r"^\s*(?:import|from)\s+([A-Za-z_][\w]*)", s, re.M):
            imports.add(m.group(1))
        if c.get("outputs"):
            has_output += 1

    headings = [ln.strip() for c in md for ln in src(c).splitlines()
                if ln.strip().startswith("#")]
    folder, base = os.path.dirname(os.path.abspath(path)), os.path.basename(path)
    missing = [(i, ref) for i, ref in reads
               if not ref.startswith("http") and not os.path.exists(os.path.join(folder, ref))]
    twin = None
    for a, b in (("_student", "_full"), ("_students", "_full_version"),
                 ("_student_version", "_full_version")):
        if a in base and os.path.exists(os.path.join(folder, base.replace(a, b))):
            twin = base.replace(a, b)
        if b in base and os.path.exists(os.path.join(folder, base.replace(b, a))):
            twin = base.replace(b, a)

    n_code = len(code)
    return {"kind": "ipynb", "file": base,
            "cells_total": len(cells), "markdown_cells": len(md), "code_cells": n_code,
            "student_written_cells": blanks,
            "student_share_pct": round(len(blanks) / float(n_code) * 100, 1) if n_code else 0.0,
            "cells_marked_do_not_change": dnc, "empty_code_cells": empty,
            "cells_with_saved_output": has_output, "headings": headings,
            "third_party_imports": sorted(x for x in imports if x not in STDLIB),
            "reads_files": reads, "missing_data_files": missing,
            "loads_from_raw_url": bool(RAW_URL.search(json.dumps(nb)[:400000])),
            "absolute_paths": abs_paths, "possible_secrets": secrets,
            "paired_version": twin}


# ================================================================ folder ====
def audit_folder(root):
    inv, notebooks, decks = {}, [], []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames
                       if d not in (".git", "__pycache__", ".ipynb_checkpoints", "node_modules")]
        for fn in filenames:
            ext = os.path.splitext(fn)[1].lower() or "(none)"
            inv[ext] = inv.get(ext, 0) + 1
            rel = os.path.relpath(os.path.join(dirpath, fn), root).replace("\\", "/")
            if ext == ".ipynb":
                notebooks.append(rel)
            elif ext in (".pptx", ".pdf", ".tex"):
                decks.append(rel)

    names = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in (".git", "__pycache__")]
        names += dirnames + list(filenames)
    joined = " ".join(names)
    conv = {
        "paired_student_and_full_versions":
            bool(re.search(r"_(student|students|student_version)\b", joined, re.I)) and
            bool(re.search(r"_(full|full_version)\b", joined, re.I)),
        "module_or_session_folders":
            bool(re.search(r"\b(module|session|week|unit|lecture)[ _-]?\d", joined, re.I)),
        "separate_dataset_folder": bool(re.search(r"\b(dataset|datasets|data)\b", joined, re.I)),
        "deliverable_csv_pattern":
            bool(re.search(r"(deliver|submission|submit)[\w-]*\.csv", joined, re.I)),
        "readme_translations": sorted(set(re.findall(r"README-([A-Za-z]{2})\.md", joined))),
        "has_license": bool(re.search(r"\bLICEN[SC]E\b", joined, re.I)),
        "has_agents_md": bool(re.search(r"\bAGENTS\.md\b", joined, re.I)),
    }
    reports = []
    for rel in sorted(notebooks):
        try:
            r = audit_ipynb(os.path.join(root, rel)); r["path"] = rel; reports.append(r)
        except Exception as e:
            reports.append({"kind": "ipynb", "path": rel, "error": str(e)})
    return {"kind": "folder", "root": os.path.abspath(root),
            "file_types": dict(sorted(inv.items(), key=lambda kv: -kv[1])),
            "notebooks": sorted(notebooks), "decks": sorted(decks),
            "conventions": conv, "notebook_reports": reports}


# ================================================================ report ====
W = 74


def print_deck(r):
    print("SOURCE: %s" % r.get("source", r["kind"]))
    print()
    print("1. HOW MANY SLIDES ARE ACTUALLY DIFFERENT")
    print("   Slides in the file:        %d" % r["slides_total"])
    print("   Repeats of a slide before: %d" % len(r["repeat_slides"]))
    print("   Different content slides:  %d" % r["distinct_slides"])
    if r.get("in_file_builds"):
        print("   Overlay / pause steps:     %d  (built into the frames themselves)"
              % r["in_file_builds"])
    for g in r["groups"]:
        print("     slides %-22s = one slide, shown %d times"
              % (", ".join(str(x) for x in g), len(g)))
    if r["needs_human_check"]:
        print("\n   The script cannot decide these. Open them and look:")
        for u in r["needs_human_check"]:
            print("     slide %-3d vs slide %-3d" % (u["slide"], u["group_head"]))
    print()

    print("2. HOW MUCH IS ON EACH SLIDE")
    print("   Words in total:            %d" % r["words_total"])
    print("   Median words per slide:    %d" % r["words_median"])
    print("   Busiest slide:             %d words" % r["words_max"])
    if r["dense_slides"]:
        print("   Slides over %d words \u2014 these are doing a document's job:" % DENSE_WORDS)
        for n, w in r["dense_slides"][:12]:
            print("     slide %-3d %d words" % (n, w))
    else:
        print("   No slide is over %d words." % DENSE_WORDS)
    print()

    print("3. QUESTIONS WRITTEN ON THE SLIDES")
    print("   Different questions asked: %d" % r["unique_questions"])
    print("   Question marks in total:   %d" % r["question_marks_total"])
    print("   Fill-in-the-blanks:        %d" % r["fill_in_blanks"])
    print("   The script cannot tell whether students get to answer. You judge that.")
    for row in r["questions_by_slide"][:20]:
        tag = "  (repeat)" if row["repeat_slide"] else ""
        print("     slide %-3d %d new%s" % (row["slide"], row["new_questions"], tag))
        for ex in row["examples"][:1]:
            print("               \"%s\"" % (ex[:80] + ("..." if len(ex) > 80 else "")))
    print()

    print("4. SPEAKER NOTES")
    if r["notes_pages"] == 0:
        print("   None at all. Nobody else could teach from this file, and students")
        print("   cannot revise whatever you say out loud.")
    else:
        print("   %d of %d slides have notes. %d have none."
              % (r["notes_pages"], r["slides_total"], r["slides_with_no_notes"]))
        for k, v in r["notes_by_kind"].items():
            print("     %-32s %2d  %s" % (k, len(v), ", ".join(str(x) for x in v) or "-"))
        live = r["notes_text"]["stage direction (live drawing)"] + \
            r["notes_text"]["short fragment - check it"]
        if live:
            print("\n   These describe teaching that exists only in the room:")
            for n, t in live:
                print("     slide %-3d \"%s\"" % (n, t[:66]))
    print()

    print("5. OTHER")
    print("   Pictures: %d   Slides with a build or animation: %s"
          % (r.get("images", 0),
             ", ".join(str(n) for n in r.get("animated_slides", [])) or "none"))
    if r.get("sections"):
        print("   Sections: %s" % "; ".join(r["sections"][:8]))
    if r.get("pages_with_no_text"):
        print("   Pages with NO text layer (picture only): %s"
              % ", ".join(str(n) for n in r["pages_with_no_text"][:15]))
        print("   The script is blind on those. Read them yourself.")


def print_ipynb(r, ind=""):
    p = lambda s: print(ind + s)
    p("CELLS")
    p("   %d cells: %d markdown, %d code."
      % (r["cells_total"], r["markdown_cells"], r["code_cells"]))
    p("")
    p("HOW MUCH DOES THE STUDENT ACTUALLY WRITE?")
    p("   Code cells left for the student: %d of %d  (%.0f%%)"
      % (len(r["student_written_cells"]), r["code_cells"], r["student_share_pct"]))
    if r["student_share_pct"] == 0:
        p("   -> Nothing. A demonstration to watch, not an exercise.")
    elif r["student_share_pct"] < 15:
        p("   -> Very little. Students mostly run someone else's code.")
    if r["paired_version"]:
        p("   Paired with: %s" % r["paired_version"])
    else:
        p("   No student/full twin found next to it.")
    p("")
    p("WILL IT RUN ON SOMEONE ELSE'S MACHINE?")
    bad = False
    for label, items in (("MISSING DATA", r["missing_data_files"]),
                         ("ABSOLUTE PATHS", r["absolute_paths"]),
                         ("POSSIBLE KEY OR TOKEN", r["possible_secrets"])):
        if items:
            bad = True
            p("   %s:" % label)
            for i, x in items[:6]:
                p("     cell %-3d %s" % (i, x))
    if not bad:
        p("   No missing files, absolute paths or keys found.")
    if r["loads_from_raw_url"]:
        p("   Loads data from a raw URL, so it runs with no local setup.")
    if r["third_party_imports"]:
        p("   Needs installed: %s" % ", ".join(r["third_party_imports"]))
    if r["headings"]:
        p("")
        p("STRUCTURE")
        for h in r["headings"][:12]:
            p("   %s" % h[:70])


def print_folder(r):
    print("WHAT IS IN THIS FOLDER")
    for ext, n in list(r["file_types"].items())[:14]:
        print("   %-8s %d" % (ext, n))
    print("\nCONVENTIONS IT ALREADY FOLLOWS")
    print("   Anything new should match these, not replace them.")
    labels = {"paired_student_and_full_versions": "student and full versions of each task",
              "module_or_session_folders": "folders named by module / session / week",
              "separate_dataset_folder": "a separate folder for data",
              "deliverable_csv_pattern": "submission is a CSV, not just the notebook",
              "has_license": "a licence file",
              "has_agents_md": "an AGENTS.md for AI coding agents"}
    for k, label in labels.items():
        print("   %-3s %s" % ("yes" if r["conventions"][k] else "no", label))
    if r["conventions"]["readme_translations"]:
        print("   yes README translated into: %s" % ", ".join(r["conventions"]["readme_translations"]))
    if r["notebook_reports"]:
        print("\nNOTEBOOKS  (%d)\n" % len(r["notebook_reports"]))
        for nb in r["notebook_reports"]:
            if "error" in nb:
                print("   %s  -- could not read: %s" % (nb["path"], nb["error"])); continue
            print("   %s" % nb["path"])
            print("      %d code cells, %.0f%% left for the student%s"
                  % (nb["code_cells"], nb["student_share_pct"],
                     ", paired with " + nb["paired_version"] if nb["paired_version"] else ""))
            flags = []
            if nb["missing_data_files"]:
                flags.append("%d missing data file(s)" % len(nb["missing_data_files"]))
            if nb["absolute_paths"]:
                flags.append("absolute paths")
            if nb["possible_secrets"]:
                flags.append("possible key in file")
            if flags:
                print("      WILL NOT RUN CLEANLY: %s" % "; ".join(flags))
    if r["decks"]:
        print("\nSLIDES  (%d)  - run this script on each separately" % len(r["decks"]))
        for d in r["decks"][:12]:
            print("   %s" % d)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("target")
    ap.add_argument("--json", dest="json_out", default=None)
    args = ap.parse_args()
    t = args.target
    if not os.path.exists(t):
        sys.exit("Not found: %s" % t)

    low = t.lower()
    if os.path.isdir(t):
        r = audit_folder(t)
    elif low.endswith(".pptx"):
        r = audit_pptx(t)
    elif low.endswith(".pdf"):
        r = audit_pdf(t)
    elif low.endswith((".tex", ".ltx")):
        r = audit_tex(t)
    elif low.endswith(".ipynb"):
        r = audit_ipynb(t)
    else:
        sys.exit("Give me a .pptx, .pdf, .tex, .ipynb or a folder. Got: %s" % t)

    if "error" in r and r["kind"] != "folder":
        print("=" * W); print("CANNOT READ %s" % os.path.basename(t)); print("=" * W)
        print("  " + r["error"]); return

    if args.json_out:
        out = dict(r); out.pop("notes_text", None)
        with open(args.json_out, "w", encoding="utf-8") as f:
            json.dump(out, f, indent=2, ensure_ascii=False, default=str)

    print("=" * W)
    print("MATERIAL AUDIT  -  %s" % os.path.basename(os.path.abspath(t)))
    print("=" * W); print()
    if r["kind"] in ("pptx", "pdf", "tex"):
        print_deck(r)
    elif r["kind"] == "ipynb":
        print_ipynb(r)
    else:
        print_folder(r)

    print()
    print("=" * W)
    print("WHAT THIS SCRIPT CANNOT SEE")
    print("=" * W)
    print("  - Anything inside a picture, chart or embedded object.")
    print("  - Whether a question on a slide is really asked, or is decoration.")
    print("  - How long anything takes in the room.")
    print("  - What you say out loud that is not written down.")
    print("  - Which topics your students get wrong every year.")
    print("  - What students are assumed to already know, and where they met it.")
    print("Everything above this line is measured. Everything a model adds after")
    print("reading the material is inference - label it as such, and turn what you")
    print("are unsure about into a question for the lecturer.")


if __name__ == "__main__":
    main()
